GET http://localhost:3001/api/auth/refreshToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2ODZhZDIwLTVkNmYtNDBkMy04NGVkLWFkOTE1OTAzYjA3MyIsInVzZXJuYW1lIjoiU3RldmUgRG9lIiwiZW1haWwiOiJzRG9lQGV4YW1wbGUuY29tIiwibG9jYXRpb24iOiJMb25kb24iLCJzcG9ydHMiOiJHeW0iLCJoYXNoZWRQYXNzd29yZCI6IiQyYiQxMCRYZ2p3QkVORHouZ2pRWmlTR0dIUThPRS9HNVFIc01MaWJqUUVRbzZPZDJ5Z0F6WHNYa1hQcSIsImlhdCI6MTY5NDM4ODc4NH0.OhoccNYOS7uYlCGTli-X-avL09dMyl5-4LdD4sxB2tU