GET http://localhost:3001/api/users/get-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkNWYxZGQ0LTdmYmEtNDhhMC04Nzc2LWJiMjUyODQ1MjczNSIsImVtYWlsIjoic0RvZUBleGFtcGxlLmNvbSIsImlhdCI6MTY5NDM4NDg1MSwiZXhwIjoxNjk0Mzg4NDUxfQ.Qd8wziZKtJyNBemg0dsn8OEyBUlzz3tem43Ke6x3tlI